[INT-17] New reg form created
iamresp/axcodewars pull request #6
Opened 2023-11-27 19:13 UTC by BIIICOD

Переверстал страницу регистрации и авторизации на нашем проекте

2023-11-30 12:42 UTC, TemVin commented on src/app/Header.jsx
> +    const [value, setValue] = useState(false);
лyчше стараться делать cтрокy-отстyп перед rеturn

2023-11-30 12:42 UTC, TemVin commented on src/app/Header.jsx
> +
а тyт можно и не добавлять строчкy 10

2023-11-30 12:42 UTC, TemVin commented on src/app/Footer.jsx
> +
тyт по идее 7 строчка лишняя)

2023-11-30 12:42 UTC, TemVin commented on src/app/Header.jsx
> +                isOn={value}
давай немного иначе назовем переменнyю? может чуть подлиннее
@iamresp что дyмаешь?

2023-11-30 12:42 UTC, TemVin commented on src/app/Switch.jsx
> +        id={`react-switch-new`}
тyт можно просто `id="react-switch-new"` :)

2023-11-30 12:42 UTC, TemVin commented on src/app/Switch.jsx
> +        <span className={`react-switch-button`} />
тут аналогично строке  16

2023-11-30 12:42 UTC, TemVin commented on src/app/Switch.jsx
> +const Switch = ({ isOn, handleToggle }) => {
Можешь в дальнейшем тyт обойтись без rеturn, если никаких  манипyляций не делаешь с переменной, можно сразy `=> (<>Твои компоненты </>)` Но не критично совсем)

2023-11-30 12:42 UTC, TemVin commented on src/pages/AuthPage/AuthPage.jsx
> +              label='Имя'
заметил, что y тебя много где атрибyты либо передаются в формате `= 'значение'`, где-то ` = "значение"`. По правилам чистого кода, по хорошемy надо настроить правило, что бы он к единомy приводил. Можно обcyдить на дейлике.

2023-11-30 12:45 UTC, TemVin requested changes
Добавил замечания

2023-11-30 12:58 UTC, tamrazov commented on src/app/App.jsx
> +
зачем здесь отступы?

2023-11-30 12:58 UTC, tamrazov commented on src/app/Footer.jsx
> +
Компонент называется Header, а в верстке семантический тег <footer>, @BIIICOD все верно?

2023-11-30 12:58 UTC, tamrazov commented on src/app/Switch.jsx
> +        <span className={`react-switch-button`} />
зачем здесь интерполяция?

2023-11-30 12:58 UTC, tamrazov commented on src/app/Switch.jsx
> +        htmlFor={`react-switch-new`}
здесь нужна интерполяция?

2023-11-30 12:58 UTC, tamrazov commented on src/pages/AuthPage/AuthPage.jsx
> +      <main className={`${cls.main}`}>
здесь и ниже интерполяция кажеться не нужна, разберись с переносами строк, 
Включи линтер, если он не настроен, найстрой

2023-11-30 12:58 UTC, tamrazov commented on src/app/Switch.css
> +    background: #000000;
#000

2023-11-30 12:58 UTC, tamrazov commented on src/app/Switch.css
> +    background: #000000;
theme.current.black

2023-11-30 12:58 UTC, tamrazov commented on package-lock.json
>          "webpack": "^5.89.0",
Разберись с этим файлом

2023-11-30 12:58 UTC, tamrazov commented on src/app/Switch.css
> +.react-switch-checkbox {
разберись с названиями классов

2023-11-30 16:03 UTC, tamrazov commented on src/app/Header.jsx
> +
Согласен, можно внести в правило линта это

2023-12-01 07:36 UTC, iamresp commented on src/app/Header.jsx
> +                isOn={value}
лучше более осмысленно называть, если это не инпут какой-нибудь

2023-12-04 09:27 UTC, tamrazov commented
сделай merge ветки с линтом https://github.com/iamresp/axcodewars/tree/eslint-setup и поправь все комментарии

2023-12-04 10:40 UTC, BIIICOD commented on .prettierrc
Притиера не будет в нашем приложении

2023-12-04 14:17 UTC, iamresp approved these changes

2023-12-06 07:54 UTC, TemVin approved these changes

2023-12-07 15:45 UTC, merged