Feature/csv-parser
iamresp/axcodewars pull request #7
Opened 2023-11-29 12:31 UTC by DemidKr

Added feature component to parse CSV file into 2d array

2023-11-30 09:32 UTC, tamrazov commented
может стоит называть МР-ы по номерам задач? что думаете @iamresp @TemVin

2023-11-30 11:12 UTC, TemVin commented
> может стоит называть МР-ы по номерам задач? что думаете @iamresp @TemVin

да, отличная идея

2023-11-30 12:45 UTC, TemVin requested changes
Добавил замечания

2023-11-30 12:45 UTC, TemVin commented on src/features/DropzoneCSV/lib/helpers.ts
> +export function ab2str(buf: ArrayBuffer) {
немного бросилось в глаза, что где-то функции через "..2..", а где-то через "..to..". Наверное, лyчше придерживаться единого стиля, можно оставить с  'to'

2023-11-30 12:45 UTC, TemVin commented on src/features/DropzoneCSV/ui/DropzoneCSV.tsx
> +                ref={inputRef} type="file"
тyт 2 атрибyта на одной строчке

2023-11-30 12:45 UTC, TemVin commented on src/features/DropzoneCSV/lib/helpers.ts
> +        if(currentData.length && currentData[currentData.length - 1].length === 0) {
сейчас, кстати, есть хорошая альтернатива array[array.length - 1] -> array.at(-1) 
@DemidKr слышал о такой штyке? это больше на развитие (https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/at)

2023-11-30 12:55 UTC, DemidKr commented on src/features/DropzoneCSV/lib/helpers.ts
> +        if(currentData.length && currentData[currentData.length - 1].length === 0) {
Да, слышал, иногда забываю пользоваться ей...

2023-11-30 12:59 UTC, DemidKr commented
> может стоит называть МР-ы по номерам задач? что думаете @iamresp @TemVin

Например как "INT-15" или как-то иначе?

2023-11-30 13:09 UTC, DemidKr commented on src/features/DropzoneCSV/lib/helpers.ts
> +export function ab2str(buf: ArrayBuffer) {
Поправил!

2023-11-30 14:56 UTC, TemVin commented
> > может стоит называть МР-ы по номерам задач? что думаете @iamresp @TemVin
> 
> Например как "INT-15" или как-то иначе?

можно:      INT-15: "что кратко сделал в рамках задачи"

2023-12-01 10:20 UTC, tamrazov commented on src/features/DropzoneCSV/ui/Dropzone.module.css
> +    top: 0;
эти свойста и ниже точно нужны? dragFile сам не становиться туда куда нужно?

2023-12-01 11:29 UTC, DemidKr commented on src/features/DropzoneCSV/ui/Dropzone.module.css
> +    top: 0;
Нет, не нужны. Остатки от первого решения

2023-12-05 10:11 UTC, DemidKr commented
Исправил конфликты

2023-12-06 07:56 UTC, TemVin approved these changes

2023-12-06 07:56 UTC, TemVin approved these changes
approvе!

2023-12-07 15:43 UTC, merged